version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum install -y docker

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 992382683074.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t mathur-flask-app .
      - docker tag mathur-flask-app:latest 992382683074.dkr.ecr.us-east-1.amazonaws.com/mathur-flask-app:latest
      - docker push 992382683074.dkr.ecr.us-east-1.amazonaws.com/mathur-flask-app:latest

  post_build:
    commands:
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"flask-app","imageUri":"992382683074.dkr.ecr.us-east-1.amazonaws.com/mathur-flask-app:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - '**/*'                 # Include all files in the current directory
    - imagedefinitions.json   # Explicitly include the imagedefinitions.json file
